name: Test

on:
  pull_request:
  push:

env:
  DOCKER_CLI_EXPERIMENTAL: "enabled"
  CGO_ENABLED: "0"

# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - linux
        arch:
          - amd64
          - arm64
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Test
        shell: bash
        run: |
          make test

      - name: Build Image
        shell: bash
        run: |
          BUILDER=${{ matrix.os }}/${{ matrix.arch }} make docker-buildx
